name: "Publish Blog with Papertown"
description: "Papertown syncs you personal markdown blog with blog platforms like dev.to"
author: "christiankohler.net"
inputs:
  root-folder:
    description: "See: https://github.com/ChristianKohler/papertown"
  devto-api-key:
    description: "See: https://github.com/ChristianKohler/papertown"
  image-root-url-github:
    description: "See: https://github.com/ChristianKohler/papertown"
  dry-run:
    description: "See: https://github.com/ChristianKohler/papertown"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  color: "white"
  icon: "upload-cloud"
